# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrimaAlmacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('causa', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
