# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_elaboracion', models.DateField(verbose_name='Fecha de elaboración')),
                ('institucion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución')),
                ('nombre_quimico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre químico')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre comercial')),
                ('formula_quimica', models.CharField(max_length=255, verbose_name='Fórmula química')),
                ('presentacion', models.IntegerField(blank=True, null=True, verbose_name='Presentación')),
                ('clasificacion', models.CharField(max_length=255, verbose_name='Clasificación')),
                ('masa_molecular', models.CharField(max_length=255, verbose_name='Masa molecular')),
                ('parametro_fisioquimicp', models.CharField(max_length=255, verbose_name='Parámetro fisioquímico')),
                ('especificacion_fisioquimica', models.IntegerField(blank=True, null=True, verbose_name='Especificación Fisioquímica')),
                ('usos_identificados', models.TextField(verbose_name='Usos identificados')),
                ('condiciones_almacenaje', models.TextField(verbose_name='Condiciones de almacenaje')),
                ('precaucion', models.TextField(blank=True, null=True, verbose_name='Precaución')),
                ('garantia', models.TextField(blank=True, null=True, verbose_name='Garantía')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
