# Generated by Django 3.2 on 2026-03-17 13:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0002_producto_prod_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEnvasado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Planificada', 'Planificada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('unidades_producidas', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_perdida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_envasado_destino', to='inventario.inv_producto')),
                ('lote_produccion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_envasado', to='inventario.inv_producto')),
                ('producto_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_envasado_destino', to='producto.producto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_envasado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
                'permissions': [('aprobar_envasado', 'Puede aprobar solicitudes de envasado'), ('ejecutar_envasado', 'Puede ejecutar el proceso de envasado')],
            },
        ),
        migrations.CreateModel(
            name='DetalleEnvasado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad_unidades', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inv_envase')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envasado.solicitudenvasado')),
            ],
            options={
                'unique_together': {('solicitud', 'presentacion')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoInsumoEnvasado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad_unidades', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inv_insumos')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='envasado.solicitudenvasado')),
            ],
            options={
                'unique_together': {('solicitud', 'insumo')},
            },
        ),
    ]
