# Generated by Django 4.2.30 on 2026-04-29 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
        ('envasado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudenvasado',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_envasado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleenvasado',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inv_envase'),
        ),
        migrations.AddField(
            model_name='detalleenvasado',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envasado.solicitudenvasado'),
        ),
        migrations.AddField(
            model_name='consumoinsumoenvasado',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inv_insumos'),
        ),
        migrations.AddField(
            model_name='consumoinsumoenvasado',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='envasado.solicitudenvasado'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleenvasado',
            unique_together={('solicitud', 'presentacion')},
        ),
        migrations.AlterUniqueTogether(
            name='consumoinsumoenvasado',
            unique_together={('solicitud', 'insumo')},
        ),
    ]
