# Generated by Django 4.2.30 on 2026-05-02 02:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_alter_vale_movimiento_almacen_tipo'),
        ('envasado', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoinsumoenvasado',
            name='cantidad_consumida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='consumoinsumoenvasado',
            name='vale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ins_envasado', to='movimientos.vale_movimiento_almacen', verbose_name='Vale de solicitud asociado a este envasado'),
        ),
        migrations.AddField(
            model_name='detalleenvasado',
            name='cantidad_consumida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='detalleenvasado',
            name='vale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='env_envasado', to='movimientos.vale_movimiento_almacen', verbose_name='Vale de solicitud asociado a este envasado'),
        ),
        migrations.AlterField(
            model_name='detalleenvasado',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envases', to='envasado.solicitudenvasado'),
        ),
        migrations.AlterField(
            model_name='solicitudenvasado',
            name='estado',
            field=models.CharField(choices=[('Planificada', 'Planificada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='Planificada', max_length=20),
        ),
    ]
