# Generated by Django 4.2.30 on 2026-05-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envasado', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudenvasado',
            name='estado',
            field=models.CharField(choices=[('Planificada', 'Planificada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='Planificada', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudenvasado',
            name='folio',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
