# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_envase_embalaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('tipoenvaseembalaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tipo_envase_embalaje.tipoenvaseembalaje')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tamanno', models.TextField(max_length=255, verbose_name='Tamaño')),
                ('material', models.TextField(max_length=255, verbose_name='Material')),
            ],
            options={
                'abstract': False,
            },
            bases=('tipo_envase_embalaje.tipoenvaseembalaje',),
        ),
    ]
