# Generated by Django 3.2 on 2025-10-20 13:13

from django.db import migrations, models
import django.db.models.deletion
import envase_embalaje.caja.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_envase_embalaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('tipoenvaseembalaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tipo_envase_embalaje.tipoenvaseembalaje')),
                ('tamanno', models.CharField(max_length=255, validators=[envase_embalaje.caja.models.validate_tamanno], verbose_name='Tamaño')),
                ('material', models.CharField(max_length=255, validators=[envase_embalaje.caja.models.validate_material], verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['nombre'],
            },
            bases=('tipo_envase_embalaje.tipoenvaseembalaje',),
        ),
    ]
