# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumosOtros',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de la materia prima')),
                ('estado', models.CharField(choices=[('comprado', 'Comprado'), ('en_almacen', 'En almacén'), ('reservado', 'Reservado')], max_length=255, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=600, verbose_name='Descripción')),
                ('cantidad_almacen', models.IntegerField(default=0, null=True, verbose_name='Cantidad')),
                ('costo', models.IntegerField(default=0, null=True, verbose_name='Costo')),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.almacen', verbose_name='Almacen ubicación')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
