# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnvaseEmbalaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=255, verbose_name='Código')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
