# Generated by Django 4.2.19 on 2025-06-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_envase_embalaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoenvaseembalaje',
            name='nombre',
            field=models.CharField(default='Tipo', max_length=255, verbose_name='Nombre'),
        ),
    ]
