# Generated by Django 3.2 on 2025-10-20 13:13

from django.db import migrations, models
import django.db.models.deletion
import envase_embalaje.tapa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0001_initial'),
        ('tipo_envase_embalaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tapa',
            fields=[
                ('tipoenvaseembalaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tipo_envase_embalaje.tipoenvaseembalaje')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.color', validators=[envase_embalaje.tapa.models.validate_color], verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tapa',
                'verbose_name_plural': 'Tapas',
                'ordering': ['nombre'],
            },
            bases=('tipo_envase_embalaje.tipoenvaseembalaje',),
        ),
    ]
