# Generated by Django 3.2 on 2025-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formato',
            options={'verbose_name': 'Formato', 'verbose_name_plural': 'Formatos'},
        ),
        migrations.AlterField(
            model_name='formato',
            name='capacidad',
            field=models.IntegerField(default=0, verbose_name='Valor de capacidad'),
        ),
    ]
