# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('tipo_materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de la materia prima')),
                ('estado', models.CharField(choices=[('comprado', 'Comprado'), ('en_almacen', 'En almacén'), ('reservado', 'Reservado')], max_length=255, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('conformacion', models.CharField(max_length=255, verbose_name='Conformación')),
                ('unidad_medida', models.CharField(max_length=255, verbose_name='Unidad de medida')),
                ('concentracion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Concentración')),
                ('cantidad_almacen', models.IntegerField(default=0, null=True, verbose_name='Cantidad')),
                ('costo', models.IntegerField(default=0, null=True, verbose_name='Costo')),
                ('ficha_tecnica', models.FileField(upload_to='', verbose_name='Ficha técnica')),
                ('hoja_seguridad', models.FileField(upload_to='', verbose_name='Hoja de seguridad')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen', verbose_name='Almacen ubicación')),
                ('tipo_materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_materia_prima.tipomateriaprima', verbose_name='Tipo de materia prima')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
