# Generated by Django 4.2.13 on 2024-10-24 01:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import produccion.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lote', models.CharField(max_length=20, unique=True, verbose_name='Lote')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('prod_result', models.BooleanField(default=False, verbose_name='Producto base')),
                ('cantidad_estimada', models.IntegerField(default=0, verbose_name='Cantidad estimada')),
                ('pruebas_quimicas', models.FileField(blank=True, null=True, upload_to=produccion.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Pruebas químicas')),
                ('costo', models.FloatField(verbose_name='Costo')),
                ('estado', models.CharField(choices=[('1', 'Formulada '), ('2', 'Ejecución'), ('3', 'Terminada'), ('4', 'Evaluada')], max_length=50, verbose_name='Estado')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planta.planta', verbose_name='Planta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sol_Prod_Base',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad_prod_base', models.IntegerField(default=1, verbose_name='Cantidad de materia prima')),
                ('lote_prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produccion.produccion', verbose_name='Lote producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sol_Mat_Primas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad_materias_primas', models.IntegerField(default=1, verbose_name='Cantidad de materia prima')),
                ('lote_prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produccion.produccion', verbose_name='Lote producto')),
                ('materia_prima_produccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materia_prima.materiaprima', verbose_name='Materia prima')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
