# Generated by Django 4.2.13 on 2024-10-24 01:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('almacen', '0001_initial'),
        ('envase_embalaje', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envasado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('1', 'Formulada '), ('2', 'Ejecución'), ('3', 'Terminada'), ('4', 'Evaluada')], max_length=255, verbose_name='Estado')),
                ('cant_prod', models.IntegerField(verbose_name='Cantidad del producto')),
                ('cant_env', models.IntegerField(verbose_name='Cantidad de envases necesarios')),
                ('almacen_det', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.almacen', verbose_name='Almacen destino')),
                ('envases', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envase_embalaje.envaseembalaje', verbose_name='Envase a utilizar')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='producto.producto', verbose_name='Producto a envasar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
