# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_sustancia_quimica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la sustancia química')),
                ('sinonimo', models.CharField(max_length=255, verbose_name='Sinónimo')),
                ('uso_recomendado', models.TextField(verbose_name='Sinónimo')),
                ('telefono_emergencia', models.IntegerField(verbose_name='Teléfono de emergencia')),
                ('clasificacion_sustancia_peligrosa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clasificación de sustancia peligrosa')),
                ('column', models.IntegerField(verbose_name='Column')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
