# Generated by Django 4.2.13 on 2024-10-24 01:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vale_Salida_Almacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consecutivo', models.IntegerField(verbose_name='Código del vale')),
                ('fecha_solicitud', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('fecha_movimiento', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.almacen', verbose_name='Almacen_origen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conduce',
            fields=[
                ('vale_salida_almacen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimientos.vale_salida_almacen')),
                ('chapa_vehiculo', models.CharField(blank=True, max_length=10, verbose_name='Chapa')),
            ],
            options={
                'abstract': False,
            },
            bases=('movimientos.vale_salida_almacen',),
        ),
    ]
