# Generated by Django 4.2.13 on 2024-10-24 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0002_envasado'),
        ('almacen', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vale_salida_almacen',
            name='solicitud_envasado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produccion.envasado', verbose_name='Envasado'),
        ),
        migrations.AddField(
            model_name='vale_salida_almacen',
            name='solicitud_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produccion.produccion', verbose_name='Producción'),
        ),
        migrations.AddField(
            model_name='conduce',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.responsable', verbose_name='Responsable del movimiento'),
        ),
    ]
