# Generated by Django 4.2.19 on 2025-07-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0002_remove_pomo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomo',
            old_name='color',
            new_name='colore',
        ),
    ]
