# Generated by Django 4.2.19 on 2025-07-24 12:22

from django.db import migrations, models
import django.db.models.deletion
import envase_embalaje.pomo.models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
        ('pomo', '0003_rename_color_pomo_colore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomo',
            name='colore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='color.color', validators=[envase_embalaje.pomo.models.validate_color], verbose_name='Color'),
        ),
    ]
