# Generated by Django 4.2.19 on 2025-07-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0004_alter_pomo_colore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomo',
            old_name='colore',
            new_name='color',
        ),
    ]
