# Generated by Django 4.2 on 2025-11-04 01:56

from django.db import migrations, models
import django.db.models.deletion
import envase_embalaje.tanque.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_envase_embalaje', '0001_initial'),
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('tipoenvaseembalaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tipo_envase_embalaje.tipoenvaseembalaje')),
                ('material', models.CharField(max_length=255, validators=[envase_embalaje.tanque.models.validate_material], verbose_name='Material')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='color.color', validators=[envase_embalaje.tanque.models.validate_color], verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
                'ordering': ['nombre'],
            },
            bases=('tipo_envase_embalaje.tipoenvaseembalaje',),
        ),
    ]
