# Generated by Django 4.2.19 on 2025-06-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanque',
            name='nombre',
        ),
    ]
