# Generated by Django 3.2.5 on 2024-11-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='propio',
            field=models.BooleanField(default=False, verbose_name='Propia'),
        ),
    ]
