# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCosto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('costo_unit_prom', models.FloatField(blank=True, default=0, null=True, verbose_name='Costo unitario promocional')),
                ('costo_maximo', models.FloatField(blank=True, default=0, null=True, verbose_name='Costo máximo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
