# Generated by Django 4.2.30 on 2026-05-03 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('propio', models.BooleanField(default=False, verbose_name='Propio')),
                ('concepto', models.CharField(choices=[('inventario', 'Inventario'), ('puntoV', 'Punto de Venta'), ('cooperada', 'Cooperada'), ('consignacion', 'Consignación'), ('planta', 'Planta de producción'), ('mixta', 'Mixta')], default='inventario', max_length=20, verbose_name='Concepto de almacen')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
            },
        ),
    ]
