# Generated by Django 3.2 on 2025-07-14 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('propio', models.BooleanField(default=False, verbose_name='Propio')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable_CI', models.CharField(blank=True, max_length=11, null=True, verbose_name='Carnet de identidad')),
                ('responsable_Nombre', models.CharField(max_length=200, null=True, verbose_name='Nombre y apellidos')),
                ('responsable_Cargo', models.CharField(max_length=200, verbose_name='Responsabilidad(cargo)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
