# Generated by Django 4.2 on 2025-11-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='concepto',
            field=models.CharField(choices=[('inventario', 'Inventario'), ('puntoV', 'Punto de Venta'), ('cooperada', 'Cooperada'), ('consignacion', 'Consignación'), ('mixta', 'Mixta')], default='inventario', max_length=20, verbose_name='Tipo de materia prima'),
        ),
    ]
