# Generated by Django 3.2 on 2026-03-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_almacen_responsable'),
        ('almacen', '0004_alter_almacen_concepto'),
    ]

    operations = [
    ]
