# Generated by Django 3.2 on 2026-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_merge_20260317_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='concepto',
            field=models.CharField(choices=[('inventario', 'Inventario'), ('puntoV', 'Punto de Venta'), ('cooperada', 'Cooperada'), ('consignacion', 'Consignación'), ('planta', 'Planta de producción'), ('mixta', 'Mixta')], default='inventario', max_length=20, verbose_name='Concepto de almacen'),
        ),
    ]
