"""
Django settings for sigem project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuración para el wizard
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

# Directorio temporal para archivos del wizard
TMP_STORAGE = os.path.join(BASE_DIR, 'tmp_wizard')
if not os.path.exists(TMP_STORAGE):
    os.makedirs(TMP_STORAGE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0&&ju^sn1)@k&!7razl4q9-jh*%w1j_o(-x2u95l%my0cmo5^l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1', 'http://localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'formtools',
    'widget_tweaks',
    'django_bootstrap5',
    'envase_embalaje.apps.EnvaseEmbalajeConfig',
    'envase_embalaje.caja.apps.EnvaseCajaConfig',
    'envase_embalaje.formato.apps.FormatoConfig',
    'envase_embalaje.pomo.apps.PomoConfig',
    'envase_embalaje.tanque.apps.TanqueConfig',
    'envase_embalaje.tapa.apps.TapaConfig',
    'envase_embalaje.tipo_envase_embalaje.apps.TipoEnvaseEmbalajeConfig',
    'ficha_costo.apps.FichaCostoConfig',
    'ficha_tecnica.apps.FichaTecnicaConfig',
    'hoja_seguridad.apps.HojaSeguridadConfig',
    'InsumosOtros.apps.InsumosotrosConfig',
    'materia_prima.apps.MateriaPrimaConfig',
    #'materia_prima.tipo_materia_prima.apps.TipoMateriaPrimaConfig',
    'movimientos.apps.MovimientosConfig',
    'nomencladores.apps.NomencladoresConfig',
    'nomencladores.almacen.apps.nomencladorAlamacenConfig',
    'nomencladores.color.apps.nomencladorColorConfig',
    'nomencladores.planta.apps.nomencladorPlantaConfig',
    'principal.apps.PrincipalConfig',
    'produccion.apps.ProduccionConfig',
    'producto.apps.ProductoConfig',
    'registro_perdida_almacen.apps.RegistroPerdidaAlmacenConfig',
    'usuario.apps.UsuarioConfig',
    'adquisiciones.apps.AdquisicionesConfig',
    'utils.apps.UtilsConfig',
    'inventario.apps.InventarioConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTH_USER_MODEL = 'usuario.CustomUser'

ROOT_URLCONF = 'sigem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'utils.context_processors.notifications',
                'materia_prima.context_processors.choices_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigem.wsgi.app'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': BASE_DIR / 'gippro_db.sqlite3',
     }
}

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'sigem',
        'USER': 'postgres',  # Local: postgres, Produccion: ardelacruz
        'PASSWORD': 'Zxcvbnm*696',  # Local: root, Produccion: Ale*2021
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
} """

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ACCOUNT_LOGOUT_REDIRECT = "login"

#SESSION_COOKIE_HTTPONLY = True  # Esto hará que las cookies de sesión no sean accesibles por scripts de JavaScript.
#CSRF_COOKIE_HTTPONLY = True  # Esto significa que la cookie no será accesible por scripts de JavaScript en el navegador y solo se enviará automáticamente en solicitudes HTTP.
#SESSION_COOKIE_SECURE = True  # Esto garantizará que las cookies de sesión solo se envíen a través de conexiones HTTPS seguras
SESSION_COOKIE_AGE = 1800  # Duración de la sesión en segundos (30 minutos)
SESSION_SAVE_EVERY_REQUEST = True  # Actualizxar la sesión en cada solicitud
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Caducar la sesión al cerrar el navegador
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
#SESSION_COOKIE_SAMESITE = 'Strict'  # Permite el envío de cookies de sesión solo a solicitudes provenientes del mismo sitio
#CSRF_COOKIE_SAMESITE = 'Strict'
# SESSION SECURITY SETTINGS
# SESSION_SECURITY_INSECURE = True
# SESSION_SECURITY_WARN_AFTER = 1800  # 30 minutos
# SESSION_SECURITY_EXPIRE_AFTER = 1800
# SESSION_SECURITY_PASSIVE_URL = ['/admin/']  # URLs donde no se aplica la seguridad de sesión
# SESSION_SECURITY_WARNING_TEMPLATE = 'gestion/session_security_warning.html'
# SESSION_SECURITY_EXPIRE_TEMPLATE = 'gestion/session_security_expire.html'

# SESSION HTTPS SETTINGS
# SECURE_HSTS_SECONDS = 31536000  # 1 año en segundos
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# # Server SETTINGS
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# #Axes config
# AXES_FAILURE_LIMIT = 5  # Número de intentos fallidos antes de bloquear
# AXES_LOCK_OUT_AT_FAILURE = True  # Bloquear una dirección IP después de superar el límite
# AXES_USE_USER_AGENT = True  # Registrar también el User-Agent en los intentos de inicio de sesión
