"""
Django settings for sigem project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0&&ju^sn1)@k&!7razl4q9-jh*%w1j_o(-x2u95l%my0cmo5^l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1', 'http://localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'adquisiciones.apps.AdquisicionConfig',
    'envase_embalaje.apps.EnvaseEmbalajeConfig',
    'envase_embalaje.caja.apps.EnvaseCajaConfig',
    'envase_embalaje.formato.apps.FormatoConfig',
    'envase_embalaje.pomo.apps.PomoConfig',
    'envase_embalaje.tanque.apps.TanqueConfig',
    'envase_embalaje.tapa.apps.TapaConfig',
    'envase_embalaje.tipo_envase_embalaje.apps.TipoEnvaseEmbalajeConfig',
    'ficha_costo.apps.FichaCostoConfig',
    'ficha_tecnica.apps.FichaTecnicaConfig',
    'hoja_seguridad.apps.HojaSeguridadConfig',
    'InsumosOtros.apps.InsumosotrosConfig',
    'materia_prima.apps.MateriaPrimaConfig',
    'materia_prima.tipo_materia_prima.apps.TipoMateriaPrimaConfig',
    'movimientos.apps.MovimientosConfig',
    'nomencladores.apps.NomencladoresConfig',
    'nomencladores.almacen.apps.nomencladorAlamacenConfig',
    'nomencladores.color.apps.nomencladorColorConfig',
    'nomencladores.planta.apps.nomencladorPlantaConfig',
    'principal.apps.PrincipalConfig',
    'produccion.apps.ProduccionConfig',
    'producto.apps.ProductoConfig',
    'registro_perdida_almacen.apps.RegistroPerdidaAlmacenConfig',
    'usuario.apps.UsuarioConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sigem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigem.wsgi.app'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.sqlite3',
#          'NAME': BASE_DIR / 'db.sqlite3',
#      }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'sigem',
        'USER': 'postgres',  # Local: postgres, Produccion: ardelacruz
        'PASSWORD': 'postgres',  # Local: root, Produccion: Ale*2021
        'HOST': '127.0.0.1',
        'PORT': '5433'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ACCOUNT_LOGOUT_REDIRECT = "login"
