# Generated by Django 4.2.19 on 2025-05-27 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMateriaPrima',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('1', 'Bases'), ('2', 'Color'), ('3', 'Conservantes'), ('4', 'Espesantes'), ('5', 'Fragancias'), ('6', 'Humectantes'), ('7', 'Otros'), ('8', 'Tensoactivos')], max_length=50, null=True, verbose_name='Tipo de materia prima')),
                ('ingrediente_activo', models.IntegerField(default=0, null=True, verbose_name='Ingrediente activo')),
                ('tipo_fragancia', models.CharField(blank=True, default='No tiene fragancia', max_length=255, null=True, verbose_name='Tipo de fragancia')),
                ('tipo_sustancia', models.CharField(blank=True, default='No tiene sustancia', max_length=255, null=True, verbose_name='Tipo de sustancia')),
                ('tipo_color', models.CharField(blank=True, default='No tiene color', max_length=255, null=True, verbose_name='Tipo de color')),
            ],
            options={
                'verbose_name': 'Tipo de materia prima',
                'verbose_name_plural': 'Tipos de materias primas',
            },
        ),
    ]
