# Generated by Django 4.2 on 2025-08-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomateriaprima',
            name='tipo',
            field=models.CharField(choices=[('Bases', 'Bases'), ('2', 'Color'), ('3', 'Conservantes'), ('4', 'Espesantes'), ('5', 'Fragancias'), ('6', 'Humectantes'), ('7', 'Otros'), ('Tensoactivos', 'Tensoactivos')], max_length=50, null=True, verbose_name='Tipo de materia prima'),
        ),
    ]
