# Generated by Django 4.2 on 2025-08-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_materia_prima', '0002_alter_tipomateriaprima_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomateriaprima',
            name='tipo',
            field=models.CharField(choices=[('Base', 'Bases'), ('Color', 'Color'), ('Conservantes', 'Conservantes'), ('Espesantes', 'Espesantes'), ('Fragancias', 'Fragancias'), ('Humectantes', 'Humectantes'), ('Otros', 'Otros'), ('Tensoactivos', 'Tensoactivos')], max_length=50, null=True, verbose_name='Tipo de materia prima'),
        ),
    ]
