# Generated by Django 4.2.13 on 2024-10-24 01:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InsumosOtros', '0001_initial'),
        ('envase_embalaje', '0001_initial'),
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_compra', models.DateTimeField(verbose_name='Fecha de la compra')),
                ('factura', models.FileField(upload_to='', verbose_name='Factura')),
                ('importada', models.BooleanField(default=False, verbose_name='Importada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrimaAdquisicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('adquisicion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adquisiciones.adquisicion', verbose_name='Adquisición de la materia prima')),
                ('materia_prima_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materia_prima.materiaprima', verbose_name='Materia prima adquirida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsumosAdquisicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('adquisicion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adquisiciones.adquisicion', verbose_name='Adquisición de insumos')),
                ('envase_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InsumosOtros.insumosotros', verbose_name='Insumo adquirido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvaseAdquisicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('adquisicion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adquisiciones.adquisicion', verbose_name='Adquisición de envase')),
                ('envase_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envase_embalaje.envaseembalaje', verbose_name='Envase o embalaje')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
